spring:
  application:
    name: prediccion-cosechas
  
  datasource:
    url: jdbc:postgresql://ep-late-water-anyvp2fy-pooler.c-6.us-east-1.aws.neon.tech/neondb?sslmode=require
    username: neondb_owner
    password: npg_Ldq0QVe1cRyI
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
      connection-timeout: 30000
      idle-timeout: 300000
      max-lifetime: 600000
      keepalive-time: 60000
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          time_zone: America/Lima
    open-in-view: false
  
  jackson:
    serialization:
      write-dates-as-timestamps: false
    time-zone: America/Lima

server:
  port: 8080
  servlet:
    context-path: /api
  error:
    include-message: always

logging:
  level:
    com.agroapp: INFO
    org.hibernate.SQL: INFO
    com.zaxxer.hikari: INFO

app:
  data:
    init: true  

# Configuración de Groq API
groq:
  api:
    key: ${GROQ_API_KEY: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}

# Configuración JWT
jwt:
  secret: ${JWT_SECRET:agroapp-secret-key-2024-prediccion-cosechas-secure}
  expiration: 86400000
